# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

minimal_mistakes_skin : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site settings
title       : Philip Davey
subtitle    : "FPGA Solutions"
email       : pjddavey@gmail.com
url         : https://philipdavey.github.io
baseurl     : "/home" # the subpath of your site, e.g. "/blog"
github_username: philipdavey
search: false

# Build settings
markdown: kramdown
remote_theme             : "mmistakes/minimal-mistakes@4.24.0"
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name     : "Philip Davey"
  avatar   : "/assets/images/bio-photo.jpg"
  bio      : "Motivated FPGA Engineer with over two years experience in the Defense industry."
  location : "Edinburgh, UK"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:pjddavey@gmail.com"
    - label: "Telephone"
      icon: "fas fa-fw fa-mobile"
      url: "tel:+447798916810"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/philipjddavey/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/philipdavey/"

footer:
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:pjddavey@gmail.com"
    - label: "Telephone"
      icon: "fas fa-fw fa-mobile"
      url: "tel:+447798916810"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/philipjddavey/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/philipdavey/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
